name: my_web_app
description: Learning Angular Dart
version: 0.0.1

dependencies:
  angular2: ^2.2.0

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.2

transformers:
- dart_to_js_script_rewriter
- angular2:
    entry_points: web/index.dart